server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2020cloud?character_set_server=utf8mb4&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #这里配的是统一的实体类包名，这样就可以在编写mapper时不用写实体类的完整名称了
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true #可以显示IP地址